name: backend lint
on:
  push:
    branches:
      - master
      - releases/**
  pull_request:

jobs:
  lint:
    name: backend lint
    runs-on: ubuntu-16.04
    timeout-minutes: 10
    env:
      MIGRATIONS_TEST_MIGRATE: 1

    steps:
      - uses: actions/checkout@v1

      # If we make these jobs "required" to merge on GH, then on every PR, GitHub automatically
      # creates a status check in the "pending" state. This means that the workflow needs to run
      # for every PR in order to update the status checks.
      #
      # In order to optimize CI usage, we want the tests to only run when python files change,
      # since frontend changes should have no effect on these test suites. We cannot use GH workflow
      # path filters because entire workflow would be skipped vs skipping individual jobs which
      # would still allow this status check to pass.
      - name: Check for python file changes
        uses: getsentry/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/file-filters.yml

      - name: Set python version output
        id: python-version
        if: steps.changes.outputs.backend == 'true'
        run: |
          echo "::set-output name=python-version::$(awk 'FNR == 2' .python-version)"

      # Until GH composite actions can use `uses`, we need to setup python here
      - uses: actions/setup-python@v2
        if: steps.changes.outputs.backend == 'true'
        with:
          python-version: ${{ steps.python-version.outputs.python-version }}

      - name: Setup pip
        uses: ./.github/actions/setup-pip
        if: steps.changes.outputs.backend == 'true'
        id: pip

      - name: pip cache
        uses: actions/cache@v2
        if: steps.changes.outputs.backend == 'true'
        with:
          path: ${{ steps.pip.outputs.pip-cache-dir }}
          key: ${{ runner.os }}-pip-py${{ steps.python-version.outputs.python-version }}-${{ hashFiles('**/requirements-*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-py${{ steps.python-version.outputs.python-version }}

      - name: Setup pre-commit
        if: steps.changes.outputs.backend == 'true'
        env:
          SENTRY_NO_VIRTUALENV_CREATION: 1
        run: |
          make setup-git

      - name: Run pre-commit on changed files
        if: steps.changes.outputs.backend == 'true'
        run: |
          # Run pre-commit to lint and format check files that were changed (but not deleted) compared to master.
          # XXX: there is a very small chance that it'll expand to exceed Linux's limits
          #      `getconf ARG_MAX` - max # bytes of args + environ for exec()
          pre-commit run --files $(git diff --diff-filter=d --name-only origin/master HEAD)
